Spreadsheet Settings
cube-planning/slate pull request #3
Opened 2019-10-16 17:20 UTC by joshholat

2019-10-16 21:35 UTC, DNU-bennett requested changes
Docs could address __why__ this endpoint exists in the first place. See my comment

2019-10-16 21:35 UTC, bennett-cube commented on source/index.html.md
> +of a spreadsheet (i.e. inside of Cube add-ons).
@joshholat If I'm an outsider or new to the code base and reading this, I wouldn't know what this means or why I'd use it. 

Maybe say something about how this endpoint returns reasonable defaults when the user hasn't specified dimensions to use for rows, columns, filters

2019-10-17 10:52 UTC, joshholat commented on source/index.html.md
> +of a spreadsheet (i.e. inside of Cube add-ons).
Updated!

2019-10-17 17:38 UTC, DNU-bennett approved these changes
:mahjong:

2019-10-17 17:39 UTC, merged